namespace DataAccessLayer.Migrations
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<DataAccessLayer.BroadwayBuilderContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "DataAccessLayer.BroadwayBuilderContext";
        }

        protected override void Seed(DataAccessLayer.BroadwayBuilderContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.

            context.Users.AddOrUpdate(x => x.UserId,
                new User { UserId = 1, Username = "joseramir1240@yahoo.com", FirstName = "Jose", LastName = "Ramirez", Age = 22, DateOfBirth = new DateTime(1996, 12, 19), City = "Los Angeles", StateProvince = "California", Country = "USA", isEnabled = true },
                new User { UserId = 2, Username = "hollow1240@gmail.com", FirstName = "Jose", LastName = "Ramirez", Age = 22, DateOfBirth = new DateTime(1996, 12, 19), City = "Los Angeles", StateProvince = "California", Country = "USA", isEnabled = true },
                new User { UserId = 3,Username= "trollingLex@yahoo.com", FirstName= "Lexzander", LastName= "Saplan", Age=23,DateOfBirth= new DateTime(1996, 03, 29),City= "Long Beach",StateProvince= "California",Country= "USA", isEnabled= true },
                new User { UserId = 4, Username = "abicastro@gmail.com", FirstName = "Abi", LastName = "Castro", Age = 22, DateOfBirth = new DateTime(1996, 07, 19), City = "Los Angeles", StateProvince = "California", Country = "USA", isEnabled = true },
                new User { UserId = 5, Username = "dramaticbryce@aol.com", FirstName = "Bryce", LastName = "Moser", Age = 26, DateOfBirth = new DateTime(1991, 05, 26), City = "New York", StateProvince = "New York", Country = "USA", isEnabled = true },
                new User { UserId = 6, Username = "abdul23@outlook.com", FirstName = "Abdul", LastName = "ohfoeshow", Age = 31, DateOfBirth = new DateTime(1988, 06, 09), City = "Las Vega", StateProvince = "Nevada", Country = "USA", isEnabled = true },
                new User { UserId = 7, Username = "sleepyabi@yahoo.com", FirstName = "Abi", LastName = "Castro", Age = 24, DateOfBirth = new DateTime(1994, 01, 05), City = "San Diego", StateProvince = "California", Country = "USA", isEnabled = true },
                new User { UserId = 8, Username = "janedoe@aol.com", FirstName = "Jane", LastName = "Doe", Age = 31, DateOfBirth = new DateTime(1988, 04, 01), City = "Houston", StateProvince = "Texas", Country = "USA", isEnabled = true },
                new User { UserId = 9, Username = "pundavidibarra@yahoo.com", FirstName = "David", LastName = "Ibarra", Age = 21, DateOfBirth = new DateTime(1997, 09, 11), City = "Los Angeles", StateProvince = "California", Country = "USA", isEnabled = true },
                new User { UserId = 10, Username = "carlosorellana@yahoo.com", FirstName = "Carlos", LastName = "Orellana", Age = 21, DateOfBirth = new DateTime(1996, 07, 18), City = "Los Angeles", StateProvince = "California", Country = "USA", isEnabled = true }
                );

            context.Theaters.AddOrUpdate(x => x.TheaterID,
                new Theater { TheaterID=1,TheaterName="Dramatic", CompanyName="Company1", StreetAddress="street", City="LA", State="CA", Country="USA", PhoneNumber="222-222-2222",DateCreated= DateTime.Now },
                new Theater { TheaterID = 2, TheaterName = "Broadway", CompanyName = "Company2", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 3, TheaterName = "Alamo", CompanyName = "Company3", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "333-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 4, TheaterName = "Dreamworks", CompanyName = "Company4", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "444-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 5, TheaterName = "Pixar", CompanyName = "Company5", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "555-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 6, TheaterName = "Lucas", CompanyName = "Company6", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "666-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 7, TheaterName = "Smash Bros", CompanyName = "Company7", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "777-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 8, TheaterName = "Raven", CompanyName = "Company8", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "888-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 9, TheaterName = "Cinemark", CompanyName = "Company9", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "999-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 10, TheaterName = "MyTheater", CompanyName = "Company10", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-111-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 11, TheaterName = "Dramatic", CompanyName = "Company1", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 12, TheaterName = "Broadway", CompanyName = "Company2", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 13, TheaterName = "Alamo", CompanyName = "Company3", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "333-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 14, TheaterName = "Dreamworks", CompanyName = "Company4", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "444-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 15, TheaterName = "Pixar", CompanyName = "Company5", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "555-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 16, TheaterName = "Lucas", CompanyName = "Company6", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "666-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 17, TheaterName = "Smash Bros", CompanyName = "Company7", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "777-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 18, TheaterName = "Raven", CompanyName = "Company8", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "888-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 19, TheaterName = "Cinemark", CompanyName = "Company9", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "999-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 20, TheaterName = "MyTheater", CompanyName = "Company10", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-111-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 21, TheaterName = "Dramatic", CompanyName = "Company1", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 22, TheaterName = "Broadway", CompanyName = "Company2", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 23, TheaterName = "Alamo", CompanyName = "Company3", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "333-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 24, TheaterName = "Dreamworks", CompanyName = "Company4", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "444-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 25, TheaterName = "Pixar", CompanyName = "Company5", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "555-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 26, TheaterName = "Lucas", CompanyName = "Company6", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "666-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 27, TheaterName = "Smash Bros", CompanyName = "Company7", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "777-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 28, TheaterName = "Raven", CompanyName = "Company8", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "888-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 29, TheaterName = "Cinemark", CompanyName = "Company9", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "999-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 30, TheaterName = "MyTheater", CompanyName = "Company10", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-111-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 31, TheaterName = "Dramatic", CompanyName = "Company1", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 32, TheaterName = "Broadway", CompanyName = "Company2", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 33, TheaterName = "Alamo", CompanyName = "Company3", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "333-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 34, TheaterName = "Dreamworks", CompanyName = "Company4", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "444-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 35, TheaterName = "Pixar", CompanyName = "Company5", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "555-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 36, TheaterName = "Lucas", CompanyName = "Company6", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "666-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 37, TheaterName = "Smash Bros", CompanyName = "Company7", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "777-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 38, TheaterName = "Raven", CompanyName = "Company8", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "888-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 39, TheaterName = "Cinemark", CompanyName = "Company9", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "999-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 40, TheaterName = "MyTheater", CompanyName = "Company10", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-111-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 41, TheaterName = "Dramatic", CompanyName = "Company1", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 42, TheaterName = "Broadway", CompanyName = "Company2", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 43, TheaterName = "Alamo", CompanyName = "Company3", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "333-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 44, TheaterName = "Dreamworks", CompanyName = "Company4", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "444-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 45, TheaterName = "Pixar", CompanyName = "Company5", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "555-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 46, TheaterName = "Lucas", CompanyName = "Company6", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "666-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 47, TheaterName = "Smash Bros", CompanyName = "Company7", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "777-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 48, TheaterName = "Raven", CompanyName = "Company8", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "888-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 49, TheaterName = "Cinemark", CompanyName = "Company9", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "999-222-2222", DateCreated = DateTime.Now },
                new Theater { TheaterID = 50, TheaterName = "MyTheater", CompanyName = "Company10", StreetAddress = "street", City = "LA", State = "CA", Country = "USA", PhoneNumber = "222-111-2222", DateCreated = DateTime.Now }
                );

            context.TheaterJobPostings.AddOrUpdate(x => x.HelpWantedID,
                new TheaterJobPosting { HelpWantedID=1, TheaterID = 1,DateCreated =DateTime.Now,Position="Position1",Description="lengthy description",Title="sometitle",Hours="20",Requirements="some reqirements",JobType="type of job"},
                new TheaterJobPosting { HelpWantedID = 2, TheaterID = 1, DateCreated = DateTime.Now, Position = "Position1", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 3, TheaterID = 1, DateCreated = DateTime.Now, Position = "Position2", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 4, TheaterID = 1, DateCreated = DateTime.Now, Position = "Position3", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 5, TheaterID = 1, DateCreated = DateTime.Now, Position = "Position4", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 6, TheaterID = 1, DateCreated = DateTime.Now, Position = "Position5", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 7, TheaterID = 1, DateCreated = DateTime.Now, Position = "Position6", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 8, TheaterID = 1, DateCreated = DateTime.Now, Position = "Position7", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 9, TheaterID = 1, DateCreated = DateTime.Now, Position = "Position8", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 10, TheaterID = 1, DateCreated = DateTime.Now, Position = "Position9", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 11, TheaterID = 2, DateCreated = DateTime.Now, Position = "Position10", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 12, TheaterID = 2, DateCreated = DateTime.Now, Position = "Position1", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 13, TheaterID = 2, DateCreated = DateTime.Now, Position = "Position2", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 14, TheaterID = 2, DateCreated = DateTime.Now, Position = "Position3", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 15, TheaterID = 2, DateCreated = DateTime.Now, Position = "Position4", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 16, TheaterID = 2, DateCreated = DateTime.Now, Position = "Position5", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 17, TheaterID = 2, DateCreated = DateTime.Now, Position = "Position6", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 18, TheaterID = 2, DateCreated = DateTime.Now, Position = "Position7", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 19, TheaterID = 2, DateCreated = DateTime.Now, Position = "Position8", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 20, TheaterID = 2, DateCreated = DateTime.Now, Position = "Position9", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 21, TheaterID = 3, DateCreated = DateTime.Now, Position = "Position10", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 22, TheaterID = 3, DateCreated = DateTime.Now, Position = "Position1", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 23, TheaterID = 3, DateCreated = DateTime.Now, Position = "Position2", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 24, TheaterID = 3, DateCreated = DateTime.Now, Position = "Position3", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 25, TheaterID = 3, DateCreated = DateTime.Now, Position = "Position4", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 26, TheaterID = 3, DateCreated = DateTime.Now, Position = "Position5", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 27, TheaterID = 3, DateCreated = DateTime.Now, Position = "Position6", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 28, TheaterID = 3, DateCreated = DateTime.Now, Position = "Position7", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 29, TheaterID = 3, DateCreated = DateTime.Now, Position = "Position8", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 30, TheaterID = 3, DateCreated = DateTime.Now, Position = "Position9", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 31, TheaterID = 4, DateCreated = DateTime.Now, Position = "Position10", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 32, TheaterID = 4, DateCreated = DateTime.Now, Position = "Position1", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 33, TheaterID = 4, DateCreated = DateTime.Now, Position = "Position2", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 34, TheaterID = 4, DateCreated = DateTime.Now, Position = "Position3", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 35, TheaterID = 4, DateCreated = DateTime.Now, Position = "Position4", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 36, TheaterID = 4, DateCreated = DateTime.Now, Position = "Position5", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 37, TheaterID = 4, DateCreated = DateTime.Now, Position = "Position6", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 38, TheaterID = 4, DateCreated = DateTime.Now, Position = "Position7", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 39, TheaterID = 4, DateCreated = DateTime.Now, Position = "Position8", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 40, TheaterID = 4, DateCreated = DateTime.Now, Position = "Position9", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 41, TheaterID = 5, DateCreated = DateTime.Now, Position = "Position10", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 42, TheaterID = 5, DateCreated = DateTime.Now, Position = "Position1", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 43, TheaterID = 5, DateCreated = DateTime.Now, Position = "Position2", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 44, TheaterID = 5, DateCreated = DateTime.Now, Position = "Position3", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 45, TheaterID = 5, DateCreated = DateTime.Now, Position = "Position4", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 46, TheaterID = 5, DateCreated = DateTime.Now, Position = "Position5", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 47, TheaterID = 5, DateCreated = DateTime.Now, Position = "Position6", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 48, TheaterID = 5, DateCreated = DateTime.Now, Position = "Position7", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 49, TheaterID = 5, DateCreated = DateTime.Now, Position = "Position8", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" },
                new TheaterJobPosting { HelpWantedID = 50, TheaterID = 5, DateCreated = DateTime.Now, Position = "Position9", Description = "lengthy description", Title = "sometitle", Hours = "20", Requirements = "some reqirements", JobType = "type of job" }
                );

            context.Productions.AddOrUpdate(x=>x.ProductionID,
                new Production { ProductionID=1, TheaterID = 1, ProductionName ="Production Name1",DirectorFirstName="DiectorF1",DirectorLastName="DirectorL1",StateProvince="state1",Street="street1",City="city1",Country="USA",Zipcode="90044"},
                new Production { ProductionID = 2, TheaterID = 1 , ProductionName = "Production Name2", DirectorFirstName = "DiectorF2", DirectorLastName = "DirectorL2", StateProvince = "state2", Street = "street2", City = "city2", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 3, TheaterID = 1, ProductionName = "Production Name3", DirectorFirstName = "DiectorF3", DirectorLastName = "DirectorL3", StateProvince = "state3", Street = "street3", City = "city3", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 4, TheaterID = 1, ProductionName = "Production Name4", DirectorFirstName = "DiectorF4", DirectorLastName = "DirectorL4", StateProvince = "state4", Street = "street4", City = "city4", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 5, TheaterID = 1, ProductionName = "Production Name5", DirectorFirstName = "DiectorF5", DirectorLastName = "DirectorL5", StateProvince = "state5", Street = "street5", City = "city5", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 6, TheaterID = 1, ProductionName = "Production Name6", DirectorFirstName = "DiectorF6", DirectorLastName = "DirectorL6", StateProvince = "state6", Street = "street6", City = "city6", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 7, TheaterID = 1, ProductionName = "Production Name7", DirectorFirstName = "DiectorF7", DirectorLastName = "DirectorL7", StateProvince = "state7", Street = "street7", City = "city7", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 8, TheaterID = 1, ProductionName = "Production Name8", DirectorFirstName = "DiectorF8", DirectorLastName = "DirectorL8", StateProvince = "state8", Street = "street8", City = "city8", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 9, TheaterID = 1, ProductionName = "Production Name9", DirectorFirstName = "DiectorF9", DirectorLastName = "DirectorL9", StateProvince = "state9", Street = "street9", City = "city9", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 10, TheaterID = 1, ProductionName = "Production Name10", DirectorFirstName = "DiectorF10", DirectorLastName = "DirectorL10", StateProvince = "state10", Street = "street10", City = "city10", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 11, TheaterID = 2, ProductionName = "Production Name1", DirectorFirstName = "DiectorF1", DirectorLastName = "DirectorL1", StateProvince = "state1", Street = "street1", City = "city1", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 12, TheaterID = 2, ProductionName = "Production Name2", DirectorFirstName = "DiectorF2", DirectorLastName = "DirectorL2", StateProvince = "state2", Street = "street2", City = "city2", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 13, TheaterID = 2, ProductionName = "Production Name3", DirectorFirstName = "DiectorF3", DirectorLastName = "DirectorL3", StateProvince = "state3", Street = "street3", City = "city3", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 14, TheaterID = 2, ProductionName = "Production Name4", DirectorFirstName = "DiectorF4", DirectorLastName = "DirectorL4", StateProvince = "state4", Street = "street4", City = "city4", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 15, TheaterID = 2, ProductionName = "Production Name5", DirectorFirstName = "DiectorF5", DirectorLastName = "DirectorL5", StateProvince = "state5", Street = "street5", City = "city5", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 16, TheaterID = 2, ProductionName = "Production Name6", DirectorFirstName = "DiectorF6", DirectorLastName = "DirectorL6", StateProvince = "state6", Street = "street6", City = "city6", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 17, TheaterID = 2, ProductionName = "Production Name7", DirectorFirstName = "DiectorF7", DirectorLastName = "DirectorL7", StateProvince = "state7", Street = "street7", City = "city7", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 18, TheaterID = 2, ProductionName = "Production Name8", DirectorFirstName = "DiectorF8", DirectorLastName = "DirectorL8", StateProvince = "state8", Street = "street8", City = "city8", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 19, TheaterID = 2, ProductionName = "Production Name9", DirectorFirstName = "DiectorF9", DirectorLastName = "DirectorL9", StateProvince = "state9", Street = "street9", City = "city9", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 20, TheaterID = 2, ProductionName = "Production Name10", DirectorFirstName = "DiectorF10", DirectorLastName = "DirectorL10", StateProvince = "state10", Street = "street10", City = "city10", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 21, TheaterID = 3, ProductionName = "Production Name1", DirectorFirstName = "DiectorF1", DirectorLastName = "DirectorL1", StateProvince = "state1", Street = "street1", City = "city1", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 22, TheaterID = 3, ProductionName = "Production Name2", DirectorFirstName = "DiectorF2", DirectorLastName = "DirectorL2", StateProvince = "state2", Street = "street2", City = "city2", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 23, TheaterID = 3, ProductionName = "Production Name3", DirectorFirstName = "DiectorF3", DirectorLastName = "DirectorL3", StateProvince = "state3", Street = "street3", City = "city3", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 24, TheaterID = 3, ProductionName = "Production Name4", DirectorFirstName = "DiectorF4", DirectorLastName = "DirectorL4", StateProvince = "state4", Street = "street4", City = "city4", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 25, TheaterID = 3, ProductionName = "Production Name5", DirectorFirstName = "DiectorF5", DirectorLastName = "DirectorL5", StateProvince = "state5", Street = "street5", City = "city5", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 26, TheaterID = 3, ProductionName = "Production Name6", DirectorFirstName = "DiectorF6", DirectorLastName = "DirectorL6", StateProvince = "state6", Street = "street6", City = "city6", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 27, TheaterID = 3, ProductionName = "Production Name7", DirectorFirstName = "DiectorF7", DirectorLastName = "DirectorL7", StateProvince = "state7", Street = "street7", City = "city7", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 28, TheaterID = 3, ProductionName = "Production Name8", DirectorFirstName = "DiectorF8", DirectorLastName = "DirectorL8", StateProvince = "state8", Street = "street8", City = "city8", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 29, TheaterID = 3, ProductionName = "Production Name9", DirectorFirstName = "DiectorF9", DirectorLastName = "DirectorL9", StateProvince = "state9", Street = "street9", City = "city9", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 30, TheaterID = 3, ProductionName = "Production Name10", DirectorFirstName = "DiectorF10", DirectorLastName = "DirectorL10", StateProvince = "state10", Street = "street10", City = "city10", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 31, TheaterID = 4, ProductionName = "Production Name1", DirectorFirstName = "DiectorF1", DirectorLastName = "DirectorL1", StateProvince = "state1", Street = "street1", City = "city1", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 32, TheaterID = 4, ProductionName = "Production Name2", DirectorFirstName = "DiectorF2", DirectorLastName = "DirectorL2", StateProvince = "state2", Street = "street2", City = "city2", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 33, TheaterID = 4, ProductionName = "Production Name3", DirectorFirstName = "DiectorF3", DirectorLastName = "DirectorL3", StateProvince = "state3", Street = "street3", City = "city3", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 34, TheaterID = 4, ProductionName = "Production Name4", DirectorFirstName = "DiectorF4", DirectorLastName = "DirectorL4", StateProvince = "state4", Street = "street4", City = "city4", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 35, TheaterID = 4, ProductionName = "Production Name5", DirectorFirstName = "DiectorF5", DirectorLastName = "DirectorL5", StateProvince = "state5", Street = "street5", City = "city5", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 36, TheaterID = 4, ProductionName = "Production Name6", DirectorFirstName = "DiectorF6", DirectorLastName = "DirectorL6", StateProvince = "state6", Street = "street6", City = "city6", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 37, TheaterID = 4, ProductionName = "Production Name7", DirectorFirstName = "DiectorF7", DirectorLastName = "DirectorL7", StateProvince = "state7", Street = "street7", City = "city7", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 38, TheaterID = 4, ProductionName = "Production Name8", DirectorFirstName = "DiectorF8", DirectorLastName = "DirectorL8", StateProvince = "state8", Street = "street8", City = "city8", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 39, TheaterID = 4, ProductionName = "Production Name9", DirectorFirstName = "DiectorF9", DirectorLastName = "DirectorL9", StateProvince = "state9", Street = "street9", City = "city9", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 40, TheaterID = 4, ProductionName = "Production Name10", DirectorFirstName = "DiectorF10", DirectorLastName = "DirectorL10", StateProvince = "state10", Street = "street10", City = "city10", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 41, TheaterID = 5, ProductionName = "Production Name1", DirectorFirstName = "DiectorF1", DirectorLastName = "DirectorL1", StateProvince = "state1", Street = "street1", City = "city1", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 42, TheaterID = 5, ProductionName = "Production Name2", DirectorFirstName = "DiectorF2", DirectorLastName = "DirectorL2", StateProvince = "state2", Street = "street2", City = "city2", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 43, TheaterID = 5, ProductionName = "Production Name3", DirectorFirstName = "DiectorF3", DirectorLastName = "DirectorL3", StateProvince = "state3", Street = "street3", City = "city3", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 44, TheaterID = 5, ProductionName = "Production Name4", DirectorFirstName = "DiectorF4", DirectorLastName = "DirectorL4", StateProvince = "state4", Street = "street4", City = "city4", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 45, TheaterID = 5, ProductionName = "Production Name5", DirectorFirstName = "DiectorF5", DirectorLastName = "DirectorL5", StateProvince = "state5", Street = "street5", City = "city5", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 46, TheaterID = 5, ProductionName = "Production Name6", DirectorFirstName = "DiectorF6", DirectorLastName = "DirectorL6", StateProvince = "state6", Street = "street6", City = "city6", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 47, TheaterID = 5, ProductionName = "Production Name7", DirectorFirstName = "DiectorF7", DirectorLastName = "DirectorL7", StateProvince = "state7", Street = "street7", City = "city7", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 48, TheaterID = 5, ProductionName = "Production Name8", DirectorFirstName = "DiectorF8", DirectorLastName = "DirectorL8", StateProvince = "state8", Street = "street8", City = "city8", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 49, TheaterID = 5, ProductionName = "Production Name9", DirectorFirstName = "DiectorF9", DirectorLastName = "DirectorL9", StateProvince = "state9", Street = "street9", City = "city9", Country = "USA", Zipcode = "90044" },
                new Production { ProductionID = 50, TheaterID = 5, ProductionName = "Production Name10", DirectorFirstName = "DiectorF10", DirectorLastName = "DirectorL10", StateProvince = "state10", Street = "street10", City = "city10", Country = "USA", Zipcode = "90044" }
                );

            context.ProductionDateTimes.AddOrUpdate(x => x.ProductionDateTimeId,
                new ProductionDateTime { ProductionDateTimeId=1, ProductionID = 1,Date = DateTime.Now,Time=new TimeSpan(2,30,00)},
                new ProductionDateTime { ProductionDateTimeId = 2, ProductionID = 1, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 3, ProductionID = 1, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 4, ProductionID = 2, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 5, ProductionID = 2, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 6, ProductionID = 2, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 7, ProductionID = 3, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 8, ProductionID = 3, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 9, ProductionID = 3, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 10, ProductionID = 4, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 11, ProductionID = 4, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 12, ProductionID = 4, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 13, ProductionID = 5, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 14, ProductionID = 5, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 15, ProductionID = 5, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 16, ProductionID = 6, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 17, ProductionID = 6, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 18, ProductionID = 6, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 19, ProductionID = 7, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 20, ProductionID = 7, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 21, ProductionID = 7, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 22, ProductionID = 8, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 23, ProductionID = 8, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 24, ProductionID = 8, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 25, ProductionID = 9, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 26, ProductionID = 9, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 27, ProductionID = 9, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 28, ProductionID = 10, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 29, ProductionID = 10, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 30, ProductionID = 10, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 31, ProductionID = 11, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 32, ProductionID = 11, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 33, ProductionID = 11, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 34, ProductionID = 12, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 35, ProductionID = 12, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 36, ProductionID = 12, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 37, ProductionID = 13, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 38, ProductionID = 13, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 39, ProductionID = 13, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 40, ProductionID = 14, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 41, ProductionID = 14, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 42, ProductionID = 14, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 43, ProductionID = 15, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 44, ProductionID = 15, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 45, ProductionID = 15, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 46, ProductionID = 16, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 47, ProductionID = 16, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 48, ProductionID = 16, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 49, ProductionID = 16, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 50, ProductionID = 16, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 51, ProductionID = 17, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 52, ProductionID = 18, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 53, ProductionID = 19, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 54, ProductionID = 20, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 55, ProductionID = 21, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 56, ProductionID = 22, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 57, ProductionID = 23, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 58, ProductionID = 24, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 59, ProductionID = 25, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 60, ProductionID = 26, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 61, ProductionID = 27, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 62, ProductionID = 28, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 63, ProductionID = 29, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 64, ProductionID = 30, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 65, ProductionID = 31, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 66, ProductionID = 32, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 67, ProductionID = 33, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 68, ProductionID = 34, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 69, ProductionID = 35, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 70, ProductionID = 36, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 71, ProductionID = 37, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 72, ProductionID = 38, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 73, ProductionID = 39, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 74, ProductionID = 40, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 75, ProductionID = 41, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 76, ProductionID = 42, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 77, ProductionID = 43, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 78, ProductionID = 44, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 79, ProductionID = 45, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 80, ProductionID = 46, Date = DateTime.Now, Time = new TimeSpan(6, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 81, ProductionID = 47, Date = DateTime.Now, Time = new TimeSpan(2, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 82, ProductionID = 48, Date = DateTime.Now, Time = new TimeSpan(3, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 83, ProductionID = 49, Date = DateTime.Now, Time = new TimeSpan(4, 30, 00) },
                new ProductionDateTime { ProductionDateTimeId = 84, ProductionID = 50, Date = DateTime.Now, Time = new TimeSpan(5, 30, 00) }

                );
            //base.Seed(context);
            
            

            
        }
    }
}
